version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/deploy
    overwrite: yes
permissions:
  - object: /home/ubuntu/deploy
    owner: root
    group: root
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/restart-codedeploy-agent.sh
      timeout: 300
      runas: root
